services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    restart: unless-stopped
    # ports:
    #   - 53:53/tcp
    #   - 53:53/udp
      # - 8081:80/tcp
    environment:
      - TZ=${TZ}
      - WEBPASSWORD=${PIHOLE_WEBPASSWORD:-changeme}
      - DNSMASQ_LISTENING=all
      - WEB_PORT=8081

    volumes:
      - ${PIHOLE_CONFIG:-./etc-pihole}:/etc/pihole
      - ${DNSMASQ_CONFIG:-./etc-dnsmasq.d}:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    network_mode: host
